version: "3.8"

services:
  backend-1:
    image: backend
    environment:
      - SERVER=1
    ports:
      - 8080
    networks:
      - loadbalance
  backend-2:
    image: backend
    environment:
      - SERVER=2
    ports:
      - 8080
    networks:
      - loadbalance
  backend-3:
    image: backend
    environment:
      - SERVER=3
    ports:
      - 8080
    networks:
      - loadbalance
  backend-4:
    image: backend
    environment:
      - SERVER=4
    ports:
      - 8080
    networks:
      - loadbalance
  nginx:
    image: nginx:alpine
    depends_on: 
      - backend-1
      - backend-2
      - backend-3
      - backend-4
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - loadbalance

networks:
  loadbalance:
